// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_company_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_company_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_company_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_company_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_company_2eproto;
namespace slowstep {
class contact;
class contactDefaultTypeInternal;
extern contactDefaultTypeInternal _contact_default_instance_;
}  // namespace slowstep
PROTOBUF_NAMESPACE_OPEN
template<> ::slowstep::contact* Arena::CreateMaybeMessage<::slowstep::contact>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace slowstep {

// ===================================================================

class contact PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:slowstep.contact) */ {
 public:
  inline contact() : contact(nullptr) {};
  virtual ~contact();

  contact(const contact& from);
  contact(contact&& from) noexcept
    : contact() {
    *this = ::std::move(from);
  }

  inline contact& operator=(const contact& from) {
    CopyFrom(from);
    return *this;
  }
  inline contact& operator=(contact&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const contact& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const contact* internal_default_instance() {
    return reinterpret_cast<const contact*>(
               &_contact_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(contact& a, contact& b) {
    a.Swap(&b);
  }
  inline void Swap(contact* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(contact* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline contact* New() const final {
    return CreateMaybeMessage<contact>(nullptr);
  }

  contact* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<contact>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const contact& from);
  void MergeFrom(const contact& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(contact* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "slowstep.contact";
  }
  protected:
  explicit contact(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_company_2eproto);
    return ::descriptor_table_company_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPeoplesFieldNumber = 1,
  };
  // repeated string peoples = 1;
  int peoples_size() const;
  private:
  int _internal_peoples_size() const;
  public:
  void clear_peoples();
  const std::string& peoples(int index) const;
  std::string* mutable_peoples(int index);
  void set_peoples(int index, const std::string& value);
  void set_peoples(int index, std::string&& value);
  void set_peoples(int index, const char* value);
  void set_peoples(int index, const char* value, size_t size);
  std::string* add_peoples();
  void add_peoples(const std::string& value);
  void add_peoples(std::string&& value);
  void add_peoples(const char* value);
  void add_peoples(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& peoples() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_peoples();
  private:
  const std::string& _internal_peoples(int index) const;
  std::string* _internal_add_peoples();
  public:

  // @@protoc_insertion_point(class_scope:slowstep.contact)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> peoples_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_company_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// contact

// repeated string peoples = 1;
inline int contact::_internal_peoples_size() const {
  return peoples_.size();
}
inline int contact::peoples_size() const {
  return _internal_peoples_size();
}
inline void contact::clear_peoples() {
  peoples_.Clear();
}
inline std::string* contact::add_peoples() {
  // @@protoc_insertion_point(field_add_mutable:slowstep.contact.peoples)
  return _internal_add_peoples();
}
inline const std::string& contact::_internal_peoples(int index) const {
  return peoples_.Get(index);
}
inline const std::string& contact::peoples(int index) const {
  // @@protoc_insertion_point(field_get:slowstep.contact.peoples)
  return _internal_peoples(index);
}
inline std::string* contact::mutable_peoples(int index) {
  // @@protoc_insertion_point(field_mutable:slowstep.contact.peoples)
  return peoples_.Mutable(index);
}
inline void contact::set_peoples(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:slowstep.contact.peoples)
  peoples_.Mutable(index)->assign(value);
}
inline void contact::set_peoples(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:slowstep.contact.peoples)
  peoples_.Mutable(index)->assign(std::move(value));
}
inline void contact::set_peoples(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  peoples_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:slowstep.contact.peoples)
}
inline void contact::set_peoples(int index, const char* value, size_t size) {
  peoples_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:slowstep.contact.peoples)
}
inline std::string* contact::_internal_add_peoples() {
  return peoples_.Add();
}
inline void contact::add_peoples(const std::string& value) {
  peoples_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:slowstep.contact.peoples)
}
inline void contact::add_peoples(std::string&& value) {
  peoples_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:slowstep.contact.peoples)
}
inline void contact::add_peoples(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  peoples_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:slowstep.contact.peoples)
}
inline void contact::add_peoples(const char* value, size_t size) {
  peoples_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:slowstep.contact.peoples)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
contact::peoples() const {
  // @@protoc_insertion_point(field_list:slowstep.contact.peoples)
  return peoples_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
contact::mutable_peoples() {
  // @@protoc_insertion_point(field_mutable_list:slowstep.contact.peoples)
  return &peoples_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace slowstep

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_company_2eproto
